//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z3_4_Ribichenko.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class garage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public garage()
        {
            this.material = new HashSet<material>();
        }
    
        public int id { get; set; }
        public int number_garage { get; set; }
        public string address { get; set; }
        public int id_type_material { get; set; }
        public int distance { get; set; }
    
        public virtual type_material type_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<material> material { get; set; }
    }
}
