//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z3_4_Ribichenko.AppDataFile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RibichenkoEntities : DbContext
    {
        private static RibichenkoEntities _context;
        public RibichenkoEntities()
            : base("name=RibichenkoEntities")
        {
        }

        public static RibichenkoEntities GetContext()
        {
            if (_context == null)
            {
                _context = new RibichenkoEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<garage> garage { get; set; }
        public virtual DbSet<material> material { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type_material> type_material { get; set; }
        public virtual DbSet<units> units { get; set; }
    }
}
